#!/bin/sh
#!/bin/sh
#!/bin/sh
#!/system/bin/sh

#echo -n input :
#read -e MOON
#echo $MOON
#sudo minicom -D /dev/ttyS0
#sudo echo "pu port             /dev/ttyS5" > zz

#[ -f "$scenfile" ] || scenfile="$LTPROOT/runtest/$scenfile"


echo "hello"
