
CROSS_COMPILE	=/home/tekkaman/working/crosstool-gcc410-k26222/gcc-4.1.0-glibc-2.3.2/arm-9tdmi-linux-gnu/bin/arm-9tdmi-linux-gnu-
CC	= $(CROSS_COMPILE)gcc


all : scull_test.o
		$(CC)  -o scull_test scull_test.o 

clean:
		rm -rf *.o *~ core .depend .*.cmd *.ko *.mod.c .tmp_versions




