#!/bin/sh

#echo -n input :
#read -e MOON
#echo $MOON
#sudo minicom -D /dev/ttyS0
#sudo echo "pu port             /dev/ttyS5" > zz

#[ -f "$scenfile" ] || scenfile="$LTPROOT/runtest/$scenfile"

#awk '{i=1; while ( i < NF ){ if ( $i ~/mo/ ) print $i;i++}}' awk-file 
dd=4
#zz=$(awk 'BEGIN{i=1}{i++;if(i==data) print $0}' data=$dd awk-file)
zz=$(awk '{i=1; while ( i < NF ){ if ( $i ~/mo/ ) print $0;i++}}' awk-file)
echo "hello"
echo $zz
