#!/bin/sh

#echo -n input :
#read -e MOON
#echo $MOON
#sudo minicom -D /dev/ttyS0
#sudo echo "pu port             /dev/ttyS5" > zz

#[ -f "$scenfile" ] || scenfile="$LTPROOT/runtest/$scenfile"

for (( i=0; i<100; i++ ))
do
for (( j=0; j<10; j++ ))
do
echo -n $i >> sed-file
done
echo "" >> sed-file
done
