#!/bin/bash

#echo -n input :
#read -e MOON
#echo $MOON
#sudo minicom -D /dev/ttyS0
#sudo echo "pu port             /dev/ttyS5" > zz

#[ -f "$scenfile" ] || scenfile="$LTPROOT/runtest/$scenfile"

num=$1
for ((i=0;i<num;i++))
do
echo hello
done
