#!/bin/bash

#awk '{i=1; while ( i < NF ){ if ( $i ~/kk/ ) print $i;i++}}' kk=$1 awk-file 
search_exit()
{
    echo "this script will exit"
    rm zz1
    exit 0
}

#grep $1 . -rn > outfile

#awk 'BEGIN{i=1;}{print "NO",i,$0;i++}' outfile
awk 'BEGIN{i=1;}{if($2=="FAIL") {print $1, $2;}i++}' result-log.5test > kk1

echo '' >>kk1

trap 'search_exit' SIGINT
testcase="hello"

line=0
while [ ${#testcase} -gt 0 ] 
do
testcase=$(awk 'BEGIN{i=0;}{ if(i==num) {print $1;} i++}' num=$line kk1) 
#echo $testcase
grep "\<$testcase\>" ./test1 -rn >> zz1

((line=$line+1))

done

#echo "testcase --------done"

echo '' zz1
#rm zz1

#path=$(awk -F":" 'BEGIN{i=0;}{i++; if(i==data) {print $2}}' data=$NUM outfile \
#path=$(awk -F":" 'BEGIN{i=0;}{i++; if(i==data) {print $1,"+"$2}}' data=$NUM outfile)
