#!/bin/bash

#awk '{i=1; while ( i < NF ){ if ( $i ~/kk/ ) print $i;i++}}' kk=$1 awk-file 
search_exit()
{
    echo "this script will exit"
    exit 0
}

#grep $1 . -rn > outfile

#awk 'BEGIN{i=1;}{print "NO",i,$0;i++}' outfile
#awk 'BEGIN{i=1;}{if($2=="PASS") {print $1, $2;}i++}' result

trap 'search_exit' SIGINT


#path=$(awk -F":" 'BEGIN{i=0;}{i++; if(i==data) {print $2}}' data=$NUM outfile \
#path=$(awk -F":" 'BEGIN{i=0;}{i++; if(i==data) {print $1,"+"$2}}' data=$NUM outfile)
awk -F":" '{ print $3}' zz
